import sys
import logging
from snakemake.io import glob_wildcards, expand
import glob,os
import pathlib
import csv
import pandas as pd
import numpy as np


#run with snakemake --profile slurm --use-conda


#import multiqc

DATADIR_SHORT="/beegfs/scratch/ric.cosr/ric.cosr/Menarini/ALL_BAM_sorted_markdup/start/"

files = []

for file_name in os.listdir(DATADIR_SHORT):
    if file_name.endswith("_markdup.bam"):
        files.append(file_name)

SUFF = []
SAMPLELIST = []
for file in files:
    A = file.split("_")[0]
    B = file.split("_")[1]
    E = A + '_' + B
    SUFF.append(E)

SUFF=set(SUFF)

SUFFIX = ' '.join(map(str, SUFF))
print("SUFFIX", SUFFIX)

#SUFFIX = "URIN101220_D10_2linfocitiadesi"
path = "logs_slurm"
try:
    os.mkdir(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s " % path)



rule all:
    input:
        expand(["coverage/{pref}_coverage.txt"], pref=SUFFIX.split(' '))


rule bTb:
    input:
        BAM = "/beegfs/scratch/ric.cosr/ric.cosr/Menarini/ALL_BAM_sorted_markdup/start/{pref}_markdup.bam",
    output:
        "coverage/{pref}_coverage.txt"
    resources: time_min = 5000, mem_mb=2500, cpus = 1
    shell:"""
        mkdir -p bed
        count=$(samtools view -F 4 -c {input.BAM})
        echo -e "{wildcards.pref}\t$count" > {output}
        """
